server.port=8081
# Logging for Phase 1 observability
logging.level.org.springframework.web=DEBUG

# Local PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-dawn-sky-a1o07loy-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7M0KQXNvkRzw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Strategy: Validate only (No writes, no schema change) [cite: 31,32]
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=super_secret_dev_key_123_upgraded_to_256_bits_for_skycompile!