server.port=8081
# Logging for Phase 1 observability
logging.level.org.springframework.web=DEBUG

# Local PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/collaborative_compiler
spring.datasource.username=parva
spring.datasource.password=parva123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Strategy: Validate only (No writes, no schema change) [cite: 31,32]
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect